// File generated by FlutterFire CLI.
// This is a placeholder file. Run 'flutterfire configure' to generate the actual configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDemo_Web_API_Key_Here',
    appId: '1:578409232570:web:276e0843e92e1005696a8',
    messagingSenderId: '578409232570',
    projectId: 'travel-b6ccd',
    authDomain: 'travel-b6ccd.firebaseapp.com',
    storageBucket: 'travel-b6ccd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDemo_Android_API_Key_Here',
    appId: '1:578409232570:android:aa334ee4d405c269696a83',
    messagingSenderId: '578409232570',
    projectId: 'travel-b6ccd',
    storageBucket: 'travel-b6ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDemo_iOS_API_Key_Here',
    appId: '1:578409232570:ios:abcdef1234567890',
    messagingSenderId: '578409232570',
    projectId: 'travel-b6ccd',
    storageBucket: 'travel-b6ccd.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDemo_macOS_API_Key_Here',
    appId: '1:578409232570:macos:abcdef1234567890',
    messagingSenderId: '578409232570',
    projectId: 'travel-b6ccd',
    storageBucket: 'travel-b6ccd.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
