# Generated by Django 5.1.4 on 2026-01-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
    ]
