# Generated by Django 5.1.4 on 2026-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_popularcity_image_remove_trip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcity',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
